"""remove full_text

Revision ID: ad78c58b2b7e
Revises: bfbf6d0924d7
Create Date: 2026-05-02 20:25:46.301128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad78c58b2b7e'
down_revision: Union[str, Sequence[str], None] = 'bfbf6d0924d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laws', 'full_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laws', sa.Column('full_text', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
