"""init

Revision ID: bfbf6d0924d7
Revises: 
Create Date: 2026-05-02 20:06:39.641047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfbf6d0924d7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('laws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('rada_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('number', sa.String(), nullable=True),
    sa.Column('date_adopted', sa.Date(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('full_text', sa.String(), nullable=True),
    sa.Column('url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('rada_id')
    )
    op.create_table('law_categories',
    sa.Column('law_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['law_id'], ['laws.id'], ),
    sa.PrimaryKeyConstraint('law_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('law_categories')
    op.drop_table('laws')
    op.drop_table('categories')
    # ### end Alembic commands ###
